### ISSUE TITLE
how to play mp4 with https

### ISSUE THREAD

**Issue by cqswxj2013** [Hiboboo/PlayerDemo#1]
E/VDVideoViewController: onError:errorCode1:100,errorCodeExtra:-1004

**Comment by Hiboboo** [comment]
这个库已经停止维护了，它有一些细节上的疑难问题没有得到更好的解决。
向你推荐另一个更好用的视频播放库，可以解决关于https播放的问题，并且有更强大的扩展功能。
[https://github.com/Bilibili/ijkplayer](url)
